-- Auto-generated from the official 512-institution KUCCPS list.
insert into institutions (name, category, type, parent_ministry, county) values
('ABERDARE TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYANDARUA'),
('AFRICA INTERNATIONAL UNIVERSITY', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('AFRICA NAZARENE UNIVERSITY', 'University', 'Private', 'Private Institution', 'KAJIADO'),
('AHMED SHAHAME MWIDANI TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MOMBASA'),
('ALDAI TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'NANDI'),
('ALUPE UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'BUSIA'),
('ALUPE UNIVERSITY TVET INSTITUTE', 'College', 'Public', 'University TVET', 'BUSIA'),
('AMREF INTERNATIONAL UNIVERSITY', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('ASUMBI TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'HOMA BAY'),
('BAHATI INSTITUTE OF BUSINESS AND ADMINISTRATION STUDIES', 'College', 'Public', 'Ministry of Education', 'NAKURU'),
('BALAMBALA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'GARISSA'),
('BANDARI MARITIME ACADEMY', 'College', 'Public', 'In Other Ministries', 'MOMBASA'),
('BARINGO NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'BARINGO'),
('BELGUT TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KERICHO'),
('BISHOP MAHON TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'TURKANA'),
('BOMET TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BOMET'),
('BOMET UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'BOMET'),
('BONDO TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'SIAYA'),
('BONDO TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'SIAYA'),
('BORABU TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYAMIRA'),
('BORABU TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYAMIRA'),
('BUKURA AGRICULTURAL COLLEGE', 'College', 'Public', 'In Other Ministries', 'KAKAMEGA'),
('BUMBE NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'BUSIA'),
('BUNGOMA NORTH TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BUNGOMA'),
('BUNYALA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BUSIA'),
('BUNYORE TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'VIHIGA'),
('BURETI TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'KERICHO'),
('BUSHIANGALA TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('BUTERE TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('BUTULA TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BUSIA'),
('CARDINAL MAURICE OTUNGA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BUNGOMA'),
('CATHOLIC UNIVERSITY OF EASTERN AFRICA', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('CENTRE FOR TOURISM TRAINING AND RESEARCH', 'College', 'Public', 'In Other Ministries', 'NAIROBI'),
('CHAMASIRI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BUSIA'),
('CHANZEYWE TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'VIHIGA'),
('CHEPALUNGU TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'BOMET'),
('CHEPSIREI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'ELGEYO MARAKWET'),
('CHERANGANY TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TRANSNZOIA'),
('CHESTA TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'WEST POKOT'),
('CHEVAYWA TECHCHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('CHUKA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('CHUKA UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'THARAKA NITHI'),
('CHUKA UNIVERSITY TVET - IGEMBE CAMPUS', 'College', 'Public', 'University TVET', 'MERU'),
('CO-OPERATIVE UNIVERSITY OF KENYA', 'University', 'Public', 'Ministry of Education', 'NAIROBI'),
('DAVID M WAMBULI TECHNICAL VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MAKUENI'),
('DAYSTAR UNIVERSITY', 'University', 'Private', 'Private Institution', 'MACHAKOS'),
('DEDAN KIMATHI UNIVERSITY OF TECHNOLOGY', 'University', 'Public', 'Ministry of Education', 'NYERI'),
('DR. DANIEL WAKO MURENDE TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BUSIA'),
('EAST AFRICAN SCHOOL OF AVIATION', 'College', 'Public', 'In Other Ministries', 'NAIROBI'),
('EASTERN KENYA INTEGRATED UNIVERSITY', 'University', 'Private', 'Private Institution', 'MACHAKOS'),
('EBUKANGA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'VIHIGA'),
('EGERTON UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'NAKURU'),
('EGOJI TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('ELDAMA RAVINE TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BARINGO'),
('ELDAS TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'WAJIR'),
('ELDORET POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'UASIN GISHU'),
('ELWAK TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MANDERA'),
('EMGWEN TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NANDI'),
('EMINING TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'BARINGO'),
('EMSOS TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'UASIN GISHU'),
('EMURUA DIKIRR TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'NAROK'),
('ENDEBESS TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'TRANSNZOIA'),
('FAYYA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TANA RIVER'),
('FRIENDS COLLEGE KAIMOSI', 'College', 'Public', 'Ministry of Education', 'VIHIGA'),
('GALANA TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'KILIFI'),
('GARISSA TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'GARISSA'),
('GARISSA UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'GARISSA'),
('GARISSA UNIVERSITY TVET INSTITUTE', 'College', 'Public', 'University TVET', 'GARISSA'),
('GARSEN TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TANA RIVER'),
('GATANGA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MURANG''A'),
('GATUNDU SOUTH TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KIAMBU'),
('GICHUGU TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KIRINYAGA'),
('GILGIL TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAKURU'),
('GITHUNGURI TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KIAMBU'),
('GITWEBE TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'NYAMIRA'),
('GODOMA TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'KILIFI'),
('GOT RAMOGI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'SIAYA'),
('GREAT LAKES UNIVERSITY OF KISUMU', 'University', 'Private', 'Private Institution', 'KISUMU'),
('GRETSA UNIVERSITY', 'University', 'Private', 'Private Institution', 'KIAMBU'),
('HEROES TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAKURU'),
('IGEMBE CENTRAL TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('IJARA TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'GARISSA'),
('IKUTHA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KITUI'),
('INTERNATIONAL LEADERSHIP UNIVERSITY', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('ISLAMIC UNIVERSITY OF KENYA', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('JARAMOGI OGINGA ODINGA UNIVERSITY OF SCIENCE AND TECHNOLOGY', 'University', 'Public', 'Ministry of Education', 'SIAYA'),
('JEREMIAH NYAGAH NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'EMBU'),
('JOMO KENYATTA UNIVERSITY OF AGRICULTURE AND TECHNOLOGY', 'University', 'Public', 'Ministry of Education', 'KIAMBU'),
('JOMO KENYATTA UNIVERSITY OF AGRICULTURE AND TECHNOLOGY TVET INSTITUTE', 'College', 'Public', 'University TVET', 'KIAMBU'),
('JOOUST CENTRE OF TECHNICAL VOCATIONAL AND EDUCATION TRAINING', 'College', 'Public', 'University TVET', 'SIAYA'),
('KABARAK UNIVERSITY', 'University', 'Private', 'Private Institution', 'NAKURU'),
('KABARNET UNIVERSITY COLLEGE', 'University', 'Public', 'Ministry of Education', 'BARINGO'),
('KABETE NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'NAIROBI'),
('KAELO TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('KAGUMO TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYERI'),
('KAIBOI NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'UASIN GISHU'),
('KAIMOSI FRIENDS UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'VIHIGA'),
('KAIMOSI TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'VIHIGA'),
('KAJIADO EAST TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KAJIADO'),
('KAJIADO WEST TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KAJIADO'),
('KAKRAO TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MIGORI'),
('KALOLENI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KILIFI'),
('KAMUKUNJI TECHNICAL VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAIROBI'),
('KAMWENJA TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYERI'),
('KANDARA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MURANG''A'),
('KAPCHEPKOR TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'BARINGO'),
('KAPCHEROP TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'ELGEYO MARAKWET'),
('KARATINA UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'NYERI'),
('KAREN TECHNICAL TRAINING INSTITUTE FOR THE DEAF', 'College', 'Public', 'Ministry of Education', 'NAIROBI'),
('KARUMO TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('KASARANI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAIROBI'),
('KASNEB', 'College', 'Public', 'In Other Ministries', 'NAIROBI'),
('KATINE TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MACHAKOS'),
('KCA UNIVERSITY', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('KENDEGE TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MIGORI'),
('KENGEN GEOTHERMAL TRAINING CENTRE', 'College', 'Public', 'In Other Ministries', 'NAKURU'),
('KENYA ASSEMBLIES OF GOD EAST UNIVERSITY', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('KENYA COAST NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'MOMBASA'),
('KENYA FORESTRY COLLEGE', 'College', 'Public', 'In Other Ministries', 'KERICHO'),
('KENYA HIGHLANDS EVANGELICAL UNIVERSITY', 'University', 'Private', 'Private Institution', 'KERICHO'),
('KENYA INDUSTRIAL TRAINING INSTITUTE', 'College', 'Public', 'In Other Ministries', 'NAKURU'),
('KENYA INSTITUTE OF HIGHWAYS AND BUILDING TECHNOLOGY', 'College', 'Public', 'In Other Ministries', 'NAIROBI'),
('KENYA INSTITUTE OF MASS COMMUNICATION', 'College', 'Public', 'In Other Ministries', 'NAIROBI'),
('KENYA INSTITUTE OF SURVEYING AND MAPPING', 'College', 'Public', 'In Other Ministries', 'NAIROBI'),
('KENYA MEDICAL TRAINING COLLEGE - AWENDO CAMPUS', 'College', 'Public', 'Ministry of Health', 'MIGORI'),
('KENYA MEDICAL TRAINING COLLEGE - BOMET CAMPUS', 'College', 'Public', 'Ministry of Health', 'BOMET'),
('KENYA MEDICAL TRAINING COLLEGE - BONDO CAMPUS', 'College', 'Public', 'Ministry of Health', 'SIAYA'),
('KENYA MEDICAL TRAINING COLLEGE - BUNGOMA CAMPUS', 'College', 'Public', 'Ministry of Health', 'BUNGOMA'),
('KENYA MEDICAL TRAINING COLLEGE - BURNT FOREST CAMPUS', 'College', 'Public', 'Ministry of Health', 'UASIN GISHU'),
('KENYA MEDICAL TRAINING COLLEGE - BUSIA CAMPUS', 'College', 'Public', 'Ministry of Health', 'BUSIA'),
('KENYA MEDICAL TRAINING COLLEGE - BUTULA CAMPUS', 'College', 'Public', 'Ministry of Health', 'BUSIA'),
('KENYA MEDICAL TRAINING COLLEGE - CHEMOLINGOT CAMPUS', 'College', 'Public', 'Ministry of Health', 'BARINGO'),
('KENYA MEDICAL TRAINING COLLEGE - CHUKA CAMPUS', 'College', 'Public', 'Ministry of Health', 'EMBU'),
('KENYA MEDICAL TRAINING COLLEGE - CHWELE CAMPUS', 'College', 'Public', 'Ministry of Health', 'BUNGOMA'),
('KENYA MEDICAL TRAINING COLLEGE - ELDORET CAMPUS', 'College', 'Public', 'Ministry of Health', 'UASIN GISHU'),
('KENYA MEDICAL TRAINING COLLEGE - EMBU CAMPUS', 'College', 'Public', 'Ministry of Health', 'EMBU'),
('KENYA MEDICAL TRAINING COLLEGE - GARISSA CAMPUS', 'College', 'Public', 'Ministry of Health', 'GARISSA'),
('KENYA MEDICAL TRAINING COLLEGE - GATUNDU - MUTUNGURU SATELLITE CAMPUS', 'College', 'Public', 'Ministry of Health', 'KIAMBU'),
('KENYA MEDICAL TRAINING COLLEGE - GATUNDU CAMPUS', 'College', 'Public', 'Ministry of Health', 'KIAMBU'),
('KENYA MEDICAL TRAINING COLLEGE - HOMA BAY - MBITA SATELLITE CAMPUS', 'College', 'Public', 'Ministry of Health', 'HOMA BAY'),
('KENYA MEDICAL TRAINING COLLEGE - HOMA BAY CAMPUS', 'College', 'Public', 'Ministry of Health', 'HOMA BAY'),
('KENYA MEDICAL TRAINING COLLEGE - IMENTI CAMPUS', 'College', 'Public', 'Ministry of Health', 'MERU'),
('KENYA MEDICAL TRAINING COLLEGE - ISIOLO CAMPUS', 'College', 'Public', 'Ministry of Health', 'ISIOLO'),
('KENYA MEDICAL TRAINING COLLEGE - ITEN CAMPUS', 'College', 'Public', 'Ministry of Health', 'ELGEYO MARAKWET'),
('KENYA MEDICAL TRAINING COLLEGE - KABARNET CAMPUS', 'College', 'Public', 'Ministry of Health', 'BARINGO'),
('KENYA MEDICAL TRAINING COLLEGE - KAKAMEGA - IKOLOMANI CAMPUS', 'College', 'Public', 'Ministry of Health', 'KAKAMEGA'),
('KENYA MEDICAL TRAINING COLLEGE - KAKAMEGA - MALAVA SATELLITE', 'College', 'Public', 'Ministry of Health', 'KAKAMEGA'),
('KENYA MEDICAL TRAINING COLLEGE - KAKAMEGA - NAVAKHOLO CAMPUS', 'College', 'Public', 'Ministry of Health', 'KAKAMEGA'),
('KENYA MEDICAL TRAINING COLLEGE - KAKAMEGA CAMPUS', 'College', 'Public', 'Ministry of Health', 'KAKAMEGA'),
('KENYA MEDICAL TRAINING COLLEGE - KANGEMA CAMPUS', 'College', 'Public', 'Ministry of Health', 'MURANG''A'),
('KENYA MEDICAL TRAINING COLLEGE - KANGUNDO CAMPUS', 'College', 'Public', 'Ministry of Health', 'MACHAKOS'),
('KENYA MEDICAL TRAINING COLLEGE - KAPENGURIA CAMPUS', 'College', 'Public', 'Ministry of Health', 'WEST POKOT'),
('KENYA MEDICAL TRAINING COLLEGE - KAPKATET CAMPUS', 'College', 'Public', 'Ministry of Health', 'KERICHO'),
('KENYA MEDICAL TRAINING COLLEGE - KAPTUMO CAMPUS', 'College', 'Public', 'Ministry of Health', 'NANDI'),
('KENYA MEDICAL TRAINING COLLEGE - KAREN - NAIROBI CAMPUS', 'College', 'Public', 'Ministry of Health', 'NAIROBI'),
('KENYA MEDICAL TRAINING COLLEGE - KARURI CAMPUS', 'College', 'Public', 'Ministry of Health', 'KIAMBU'),
('KENYA MEDICAL TRAINING COLLEGE - KERIO VALLEY CAMPUS', 'College', 'Public', 'Ministry of Health', 'ELGEYO MARAKWET'),
('KENYA MEDICAL TRAINING COLLEGE - KILIFI CAMPUS', 'College', 'Public', 'Ministry of Health', 'KILIFI'),
('KENYA MEDICAL TRAINING COLLEGE - KINANGOP CAMPUS', 'College', 'Public', 'Ministry of Health', 'NYANDARUA'),
('KENYA MEDICAL TRAINING COLLEGE - KISII CAMPUS', 'College', 'Public', 'Ministry of Health', 'KISII'),
('KENYA MEDICAL TRAINING COLLEGE - KISUMU CAMPUS', 'College', 'Public', 'Ministry of Health', 'KISUMU'),
('KENYA MEDICAL TRAINING COLLEGE - KITALE CAMPUS', 'College', 'Public', 'Ministry of Health', 'TRANSNZOIA'),
('KENYA MEDICAL TRAINING COLLEGE - KITUI - MUTOMO CAMPUS', 'College', 'Public', 'Ministry of Health', 'KITUI'),
('KENYA MEDICAL TRAINING COLLEGE - KITUI CAMPUS', 'College', 'Public', 'Ministry of Health', 'KITUI'),
('KENYA MEDICAL TRAINING COLLEGE - KOMBEWA CAMPUS', 'College', 'Public', 'Ministry of Health', 'KISUMU'),
('KENYA MEDICAL TRAINING COLLEGE - KURIA CAMPUS', 'College', 'Public', 'Ministry of Health', 'MIGORI'),
('KENYA MEDICAL TRAINING COLLEGE - KWALE CAMPUS', 'College', 'Public', 'Ministry of Health', 'KWALE'),
('KENYA MEDICAL TRAINING COLLEGE - LAKE VICTORIA CAMPUS', 'College', 'Public', 'Ministry of Health', 'KISUMU'),
('KENYA MEDICAL TRAINING COLLEGE - LAMU CAMPUS', 'College', 'Public', 'Ministry of Health', 'LAMU'),
('KENYA MEDICAL TRAINING COLLEGE - LODWAR CAMPUS', 'College', 'Public', 'Ministry of Health', 'TURKANA'),
('KENYA MEDICAL TRAINING COLLEGE - LOITOKITOK CAMPUS', 'College', 'Public', 'Ministry of Health', 'KAJIADO'),
('KENYA MEDICAL TRAINING COLLEGE - LUGARI CAMPUS', 'College', 'Public', 'Ministry of Health', 'KAKAMEGA'),
('KENYA MEDICAL TRAINING COLLEGE - MACHAKOS CAMPUS', 'College', 'Public', 'Ministry of Health', 'MACHAKOS'),
('KENYA MEDICAL TRAINING COLLEGE - MAKINDU CAMPUS', 'College', 'Public', 'Ministry of Health', 'MAKUENI'),
('KENYA MEDICAL TRAINING COLLEGE - MAKUENI - MBUVO CAMPUS', 'College', 'Public', 'Ministry of Health', 'MAKUENI'),
('KENYA MEDICAL TRAINING COLLEGE - MAKUENI CAMPUS', 'College', 'Public', 'Ministry of Health', 'MAKUENI'),
('KENYA MEDICAL TRAINING COLLEGE - MANDERA CAMPUS', 'College', 'Public', 'Ministry of Health', 'MANDERA'),
('KENYA MEDICAL TRAINING COLLEGE - MANZA CAMPUS', 'College', 'Public', 'Ministry of Health', 'MACHAKOS'),
('KENYA MEDICAL TRAINING COLLEGE - MARIMANTI CAMPUS', 'College', 'Public', 'Ministry of Health', 'THARAKA NITHI'),
('KENYA MEDICAL TRAINING COLLEGE - MARSABIT CAMPUS', 'College', 'Public', 'Ministry of Health', 'MARSABIT'),
('KENYA MEDICAL TRAINING COLLEGE - MATHARE CAMPUS', 'College', 'Public', 'Ministry of Health', 'NAIROBI'),
('KENYA MEDICAL TRAINING COLLEGE - MAUA CAMPUS', 'College', 'Public', 'Ministry of Health', 'MERU'),
('KENYA MEDICAL TRAINING COLLEGE - MBOONI CAMPUS', 'College', 'Public', 'Ministry of Health', 'MAKUENI'),
('KENYA MEDICAL TRAINING COLLEGE - MERU - MIATHENE SATELLITE CAMPUS', 'College', 'Public', 'Ministry of Health', 'MERU'),
('KENYA MEDICAL TRAINING COLLEGE - MERU CAMPUS', 'College', 'Public', 'Ministry of Health', 'MERU'),
('KENYA MEDICAL TRAINING COLLEGE - MIGORI CAMPUS', 'College', 'Public', 'Ministry of Health', 'MIGORI'),
('KENYA MEDICAL TRAINING COLLEGE - MOLO CAMPUS', 'College', 'Public', 'Ministry of Health', 'NAKURU'),
('KENYA MEDICAL TRAINING COLLEGE - MOMBASA CAMPUS', 'College', 'Public', 'Ministry of Health', 'MOMBASA'),
('KENYA MEDICAL TRAINING COLLEGE - MOSORIOT CAMPUS', 'College', 'Public', 'Ministry of Health', 'NANDI'),
('KENYA MEDICAL TRAINING COLLEGE - MSAMBWENI CAMPUS', 'College', 'Public', 'Ministry of Health', 'KWALE'),
('KENYA MEDICAL TRAINING COLLEGE - MURANG''A CAMPUS', 'College', 'Public', 'Ministry of Health', 'MURANG''A'),
('KENYA MEDICAL TRAINING COLLEGE - MWINGI CAMPUS', 'College', 'Public', 'Ministry of Health', 'KITUI'),
('KENYA MEDICAL TRAINING COLLEGE - NAIROBI CAMPUS', 'College', 'Public', 'Ministry of Health', 'NAIROBI'),
('KENYA MEDICAL TRAINING COLLEGE - NAKURU CAMPUS', 'College', 'Public', 'Ministry of Health', 'NAKURU'),
('KENYA MEDICAL TRAINING COLLEGE - NAROK CAMPUS', 'College', 'Public', 'Ministry of Health', 'NAROK'),
('KENYA MEDICAL TRAINING COLLEGE - NDHIWA CAMPUS', 'College', 'Public', 'Ministry of Health', 'HOMA BAY'),
('KENYA MEDICAL TRAINING COLLEGE - NYAHURURU CAMPUS', 'College', 'Public', 'Ministry of Health', 'LAIKIPIA'),
('KENYA MEDICAL TRAINING COLLEGE - NYAMACHE - GUCHA SATELLITE', 'College', 'Public', 'Ministry of Health', 'KISII'),
('KENYA MEDICAL TRAINING COLLEGE - NYAMACHE CAMPUS', 'College', 'Public', 'Ministry of Health', 'KISII'),
('KENYA MEDICAL TRAINING COLLEGE - NYAMIRA CAMPUS', 'College', 'Public', 'Ministry of Health', 'NYAMIRA'),
('KENYA MEDICAL TRAINING COLLEGE - NYANDARUA CAMPUS', 'College', 'Public', 'Ministry of Health', 'NYANDARUA'),
('KENYA MEDICAL TRAINING COLLEGE - NYERI - MUKURUWEINI SATELLITE CAMPUS', 'College', 'Public', 'Ministry of Health', 'NYERI'),
('KENYA MEDICAL TRAINING COLLEGE - NYERI CAMPUS', 'College', 'Public', 'Ministry of Health', 'NYERI'),
('KENYA MEDICAL TRAINING COLLEGE - OTHAYA CAMPUS', 'College', 'Public', 'Ministry of Health', 'NYERI'),
('KENYA MEDICAL TRAINING COLLEGE - PORT REITZ CAMPUS', 'College', 'Public', 'Ministry of Health', 'MOMBASA'),
('KENYA MEDICAL TRAINING COLLEGE - RACHUONYO CAMPUS', 'College', 'Public', 'Ministry of Health', 'HOMA BAY'),
('KENYA MEDICAL TRAINING COLLEGE - RERA CAMPUS', 'College', 'Public', 'Ministry of Health', 'SIAYA'),
('KENYA MEDICAL TRAINING COLLEGE - SHIANDA - MUMIAS CAMPUS', 'College', 'Public', 'Ministry of Health', 'KAKAMEGA'),
('KENYA MEDICAL TRAINING COLLEGE - SIAYA CAMPUS', 'College', 'Public', 'Ministry of Health', 'SIAYA'),
('KENYA MEDICAL TRAINING COLLEGE - SIGOWET CAMPUS', 'College', 'Public', 'Ministry of Health', 'KERICHO'),
('KENYA MEDICAL TRAINING COLLEGE - TANA RIVER CAMPUS', 'College', 'Public', 'Ministry of Health', 'TANA RIVER'),
('KENYA MEDICAL TRAINING COLLEGE - TAVETA CAMPUS', 'College', 'Public', 'Ministry of Health', 'TAITA TAVETA'),
('KENYA MEDICAL TRAINING COLLEGE - TESO CAMPUS', 'College', 'Public', 'Ministry of Health', 'BUSIA'),
('KENYA MEDICAL TRAINING COLLEGE - THIKA CAMPUS', 'College', 'Public', 'Ministry of Health', 'KIAMBU'),
('KENYA MEDICAL TRAINING COLLEGE - TRANS MARA CAMPUS', 'College', 'Public', 'Ministry of Health', 'NAROK'),
('KENYA MEDICAL TRAINING COLLEGE - UGENYA CAMPUS', 'College', 'Public', 'Ministry of Health', 'SIAYA'),
('KENYA MEDICAL TRAINING COLLEGE - UGUNJA CAMPUS', 'College', 'Public', 'Ministry of Health', 'SIAYA'),
('KENYA MEDICAL TRAINING COLLEGE - VIHIGA CAMPUS', 'College', 'Public', 'Ministry of Health', 'VIHIGA'),
('KENYA MEDICAL TRAINING COLLEGE - VOI CAMPUS', 'College', 'Public', 'Ministry of Health', 'TAITA TAVETA'),
('KENYA MEDICAL TRAINING COLLEGE - WAJIR CAMPUS', 'College', 'Public', 'Ministry of Health', 'WAJIR'),
('KENYA MEDICAL TRAINING COLLEGE - WEBUYE CAMPUS', 'College', 'Public', 'Ministry of Health', 'BUNGOMA'),
('KENYA MEDICAL TRAINING COLLEGE - YATTA CAMPUS', 'College', 'Public', 'Ministry of Health', 'MACHAKOS'),
('KENYA METHODIST UNIVERSITY', 'University', 'Private', 'Private Institution', 'MERU'),
('KENYA SCHOOL OF AGRICULTURE', 'College', 'Public', 'In Other Ministries', 'NYERI'),
('KENYA SCHOOL OF AGRICULTURE - AINABKOI CAMPUS', 'College', 'Public', 'In Other Ministries', 'UASIN GISHU'),
('KENYA SCHOOL OF AGRICULTURE - UGENYA CAMPUS', 'College', 'Public', 'In Other Ministries', 'SIAYA'),
('KENYA SCHOOL OF AGRICULTURE SONGA MBELE CAMPUS', 'College', 'Public', 'Ministry of Education', 'MURANG''A'),
('KENYA SCHOOL OF LAW', 'College', 'Public', 'In Other Ministries', 'NAIROBI'),
('KENYA TECHNICAL TRAINERS COLLEGE', 'College', 'Public', 'NULL', 'NAIROBI'),
('KENYA UTALII COLLEGE', 'College', 'Public', 'Ministry of Tourism', 'NAIROBI'),
('KENYA UTALII COLLEGE - RONALD NGALA', 'College', 'Public', 'Ministry of Tourism', 'KILIFI'),
('KENYA WATER INSTITUTE', 'College', 'Public', 'In Other Ministries', 'NAIROBI'),
('KENYA WILDLIFE SERVICE TRAINING INSTITUTE', 'College', 'Public', 'In Other Ministries', 'NAKURU'),
('KENYATTA UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'NAIROBI'),
('KENYATTA UNIVERSITY - CITY CAMPUS, TVET CENTRE', 'College', 'Public', 'University TVET', 'NAIROBI'),
('KENYATTA UNIVERSITY TVET - KITUI', 'College', 'Public', 'University TVET', 'KITUI'),
('KENYATTA UNIVERSITY TVET - MAIN CAMPUS', 'College', 'Public', 'University TVET', 'NAIROBI'),
('KENYATTA UNIVERSITY TVET - MOMBASA', 'College', 'Public', 'University TVET', 'MOMBASA'),
('KENYATTA UNIVERSITY TVET - NAKURU', 'College', 'Public', 'University TVET', 'NAKURU'),
('KENYENYA TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'KISII'),
('KERICHO TEACHERS'' COLLEGE', 'College', 'Public', 'Ministry of Education', 'KERICHO'),
('KERICHO TOWNSHIP TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KERICHO'),
('KERIO VALLEY TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'ELGEYO MARAKWET'),
('KERIO VALLEY UNIVERSITY COLLEGE', 'University', 'Public', 'Ministry of Education', 'ELGEYO MARAKWET'),
('KEROKA TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'KISII'),
('KHWISERO TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('KIAMBU NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'KIAMBU'),
('KIBABII DIPLOMA TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'BUNGOMA'),
('KIBABII UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'BUNGOMA'),
('KIBABII UNIVERSITY DIRECTORATE OF TVET COLLEGE', 'College', 'Public', 'University TVET', 'BUNGOMA'),
('KIBRA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAIROBI'),
('KIBWEZI TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MAKUENI'),
('KIENI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYERI'),
('KIGUMO TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MURANG''A'),
('KIHARU TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MURANG''A'),
('KIIRUA TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('KILGORIS TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAROK'),
('KIMASIAN TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KERICHO'),
('KIMININI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TRANSNZOIA'),
('KINANGO TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KWALE'),
('KINANGOP TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYANDARUA'),
('KIPIPIRI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYANDARUA'),
('KIPKABUS TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'UASIN GISHU'),
('KIPSINENDE TECHNICAL VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KERICHO'),
('KIPSOEN TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'ELGEYO MARAKWET'),
('KIPTARAGON TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAKURU'),
('KIRINYAGA CENTRAL TECHNICAL& VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KIRINYAGA'),
('KIRINYAGA UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'KIRINYAGA'),
('KIRIRI WOMENS UNIVERSITY OF SCIENCE AND TECHNOLOGY', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('KISII NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'KISII'),
('KISII UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'KISII'),
('KISII UNIVERSITY TVET INSTITUTE', 'College', 'Public', 'University TVET', 'KISII'),
('KISIWA TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'BUNGOMA'),
('KISUMU INSTITUTE OF COMMUNITY DEVELOPMENT TRAINING', 'College', 'Private', 'Private Institution', 'KISUMU'),
('KISUMU POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'KISUMU'),
('KITALE NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'TRANSNZOIA'),
('KITELAKAPEL TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'WEST POKOT'),
('KITUI EAST TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KITUI'),
('KITUI RURAL TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KITUI'),
('KITUI TEACHERS TECHNICAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KITUI'),
('KITUI TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'KITUI'),
('KITUTU CHACHE TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KISII'),
('KITUTU MASABA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYAMIRA'),
('KOITALEEL SAMOEI UNIVERSITY COLLEGE', 'University', 'Public', 'Ministry of Education', 'NANDI'),
('KONGONI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('KONOIN TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'BOMET'),
('KOSHIN TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'UASIN GISHU'),
('KWALE TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'KWALE'),
('LAGDERA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'GARISSA'),
('LAIKIPIA EAST TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'LAIKIPIA'),
('LAIKIPIA NORTH TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'LAIKIPIA'),
('LAIKIPIA UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'LAIKIPIA'),
('LAIKIPIA UNIVERSITY TVET INSTITUTE', 'College', 'Public', 'University TVET', 'LAIKIPIA'),
('LAIKIPIA WEST TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'LAIKIPIA'),
('LAISAMIS TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MARSABIT'),
('LAMU EAST TECHCHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'LAMU'),
('LAMU WEST TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'LAMU'),
('LANGATA TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAIROBI'),
('LARI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KIAMBU'),
('LIKONI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MOMBASA'),
('LIMURU TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KIAMBU'),
('LODWAR TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TURKANA'),
('LOIMA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TURKANA'),
('LUANDA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'VIHIGA'),
('LUGARI DIPLOMA TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('LUKENYA UNIVERSITY', 'University', 'Private', 'Private Institution', 'MACHAKOS'),
('LUNGA LUNGA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KWALE'),
('MAASAI MARA TECHNICAL VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAROK'),
('MAASAI MARA UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'NAROK'),
('MAASAI MARA UNIVERSITY TVET INSTITUTE', 'College', 'Public', 'University TVET', 'NAROK'),
('MABERA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MIGORI'),
('MACHAKOS TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'MACHAKOS'),
('MACHAKOS TECHNICAL INSTITUTE FOR THE BLIND', 'College', 'Public', 'Ministry of Education', 'MACHAKOS'),
('MACHAKOS TOWN TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MACHAKOS'),
('MACHAKOS UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'MACHAKOS'),
('MACHAKOS UNIVERSITY TVET INSTITUTE', 'College', 'Public', 'University TVET', 'MACHAKOS'),
('MAGARINI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KILIFI'),
('MAKUENI UNIVERSITY COLLEGE', 'University', 'Public', 'Ministry of Education', 'MAKUENI'),
('MAMA NGINA UNIVERSITY COLLEGE', 'University', 'Public', 'Ministry of Education', 'KIAMBU'),
('MANAGEMENT UNIVERSITY OF AFRICA', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('MANDERA TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'MANDERA'),
('MANDERA TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MANDERA'),
('MANYATTA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'EMBU'),
('MARIST INTERNATIONAL UNIVERSITY COLLEGE', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('MASAI TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'KAJIADO'),
('MASENO UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'KISUMU'),
('MASINDE MULIRO UNIVERSITY OF SCIENCE & TECHNOLOGY', 'University', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('MASINDE MULIRO UNIVERSITY OF SCIENCE AND TECHNOLOGY TVET COLLEGE ,WEBUYE', 'College', 'Public', 'University TVET', 'BUNGOMA'),
('MASINDE MULIRO UNIVERSITY OF SCIENCE AND TECHNOLOGY TVET INSTITUTE', 'College', 'Public', 'University TVET', 'KAKAMEGA'),
('MASINGA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MACHAKOS'),
('MATHENGE TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'NYERI'),
('MATHIOYA TECHNICAL VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MURANG''A'),
('MATHIRA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYERI'),
('MATILI TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'BUNGOMA'),
('MATUGA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KWALE'),
('MAWEGO NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'HOMA BAY'),
('MBEERE NORTH TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'EMBU'),
('MBITA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'HOMA BAY'),
('MERTI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'ISIOLO'),
('MERU UNIVERSITY OF SCIENCE AND TECHNOLOGY TVET DIRECTORATE', 'College', 'Public', 'University TVET', 'MERU'),
('MERU NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'MERU'),
('MERU TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('MERU UNIVERSITY OF SCIENCE AND TECHNOLOGY', 'University', 'Public', 'Ministry of Education', 'MERU'),
('MICHUKI NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'MURANG''A'),
('MIGORI TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'MIGORI'),
('MITUNGUU TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('MOCHONGOI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TURKANA'),
('MOI TEACHERS COLLEGE - BARINGO', 'College', 'Public', 'Ministry of Education', 'BARINGO'),
('MOI UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'UASIN GISHU'),
('MOI UNIVERSITY TVET INSTITUTE', 'College', 'Public', 'University TVET', 'UASIN GISHU'),
('MOIBEN TECHNICAL VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'UASIN GISHU'),
('MOLO TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAKURU'),
('MORENDAT INSTITUTE OF OIL AND GAS', 'College', 'Public', 'In Other Ministries', 'NAIROBI'),
('MOSORIOT TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'NANDI'),
('MOUNT KENYA UNIVERSITY', 'University', 'Private', 'Private Institution', 'KIAMBU'),
('MSAMBWENI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KWALE'),
('MUKIRIA TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('MUKURWEINI TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'NYERI'),
('MULANGO TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KITUI'),
('MULTIMEDIA UNIVERSITY OF KENYA', 'University', 'Public', 'Ministry of Education', 'NAIROBI'),
('MULTIMEDIA UNIVERSITY OF KENYA TVET CENTRE', 'College', 'Public', 'University TVET', 'NAIROBI'),
('MUMIAS WEST TECHNICAL VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('MUNGATSI TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BUSIA'),
('MURAGA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('MURANG''A TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'MURANG''A'),
('MURANG''A TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MURANG''A'),
('MURANG''A UNIVERSITY OF TECHNOLOGY', 'University', 'Public', 'Ministry of Education', 'MURANG''A'),
('MURANG''A UNIVERSITY OF TECHNOLOGY TVET INSTITUTE', 'College', 'Public', 'University TVET', 'MURANG''A'),
('MUSAKASA TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'BUNGOMA'),
('MVITA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MOMBASA'),
('MWALA TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MACHAKOS'),
('MWATATE TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TAITA TAVETA'),
('MWEA TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KIRINYAGA'),
('NACHU TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KIAMBU'),
('NAIVASHA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAKURU'),
('NAROK SOUTH TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAROK'),
('NAROK TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAROK'),
('NAROK WEST TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'NAROK'),
('NAVAKHOLO TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('NDARAGWA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYANDARUA'),
('NDIA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KIRINYAGA'),
('NGERIA TECHNICAL TRAINING INSTITITUON', 'College', 'Public', 'Ministry of Education', 'UASIN GISHU'),
('NGONG TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KAJIADO'),
('NJORO TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'NAKURU'),
('NKABUNE TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('NORTH EASTERN NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'GARISSA'),
('NORTH HORR TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MARSABIT'),
('NORTH RIFT TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BARINGO'),
('NUU TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KITUI'),
('NYAKACH TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KISUMU'),
('NYAMIRA NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'NYAMIRA'),
('NYANDARUA NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'NYANDARUA'),
('NYANDARUA UNIVERSITY COLLEGE', 'University', 'Public', 'Ministry of Education', 'NYANDARUA'),
('NYANDO TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KISUMU'),
('NYERI NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'NYERI'),
('OKAME TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BUSIA'),
('OL KALOU TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYANDARUA'),
('OL''LESSOS NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'NANDI'),
('OMUGA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'HOMA BAY'),
('OPEN UNIVERSITY OF KENYA', 'University', 'Public', 'Ministry of Education', 'MACHAKOS'),
('OROGARE TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KISII'),
('OUTSPAN GLOBAL UNIVERSITY', 'University', 'Private', 'Private Institution', 'NYERI'),
('PAN AFRICA CHRISTIAN UNIVERSITY', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('PC KINYANJUI TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'NAIROBI'),
('PIONEER INTERNATIONAL UNIVERSITY', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('PRESBYTERIAN UNIVERSITY OF EAST AFRICA', 'University', 'Private', 'Private Institution', 'KIAMBU'),
('PWANI UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'KILIFI'),
('PWANI UNIVERSITY TVET COLLEGE', 'College', 'Public', 'University TVET', 'KILIFI'),
('RACHUONYO TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'HOMA BAY'),
('RAILWAY TRAINING INSTITUTE', 'College', 'Public', 'In Other Ministries', 'NAIROBI'),
('RAMOGI INSTITUTE OF ADVANCE TECHNOLOGY', 'College', 'Public', 'Ministry of Education', 'KISUMU'),
('RANGWE TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'HOMA BAY'),
('RARIEDA TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'SIAYA'),
('REGIONAL CENTRE FOR MAPPING OF RESOURCES FOR DEVELOPMENT', 'College', 'Public', 'In Other Ministries', 'NAIROBI'),
('RIAMO TECHNICAL VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KISII'),
('RIARA UNIVERSITY', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('RIATIRIMBA TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KISII'),
('RIFT VALLEY INSTITUTE OF SCIENCE AND TECHNOLOGY', 'College', 'Public', 'Ministry of Education', 'NAKURU'),
('RIFT VALLEY TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'UASIN GISHU'),
('RIRAGIA TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'KISII'),
('RONGO UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'MIGORI'),
('RONGO UNIVERSITY TECHNICAL & VOCATIONAL TRAINING INSTITUTE', 'College', 'Public', 'University TVET', 'MIGORI'),
('RUIRU TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KIAMBU'),
('RUNYENJES TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'EMBU'),
('SABATIA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'VIHIGA'),
('SAMBURU NORTH TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'SAMBURU'),
('SAMBURU TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'SAMBURU'),
('SCOTT CHRISTIAN UNIVERSITY', 'University', 'Private', 'Private Institution', 'MACHAKOS'),
('SEKU DIRECTORATE OF TVET WOTE CAMPUS', 'College', 'Public', 'University TVET', 'MAKUENI'),
('SEME TEACHERS COLLEGE', 'College', 'Public', 'Ministry of Education', 'KISUMU'),
('SEME TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KISUMU'),
('SHAMBERERE TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('SHANZU TEACHERS TECHNICAL TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'MOMBASA'),
('SHANZU TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'MOMBASA'),
('SIALA TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MIGORI'),
('SIAYA NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'SIAYA'),
('SIGALAGALA NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('SIKRI TECHNICAL TRAINING INSTITUTE FOR THE BLIND AND DEAF', 'College', 'Public', 'Ministry of Education', 'HOMA BAY'),
('SIRISIA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BUNGOMA'),
('SIRUTI TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MIGORI'),
('SOT TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'BOMET'),
('SOTIK TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'BOMET'),
('SOUTH EASTERN KENYA UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'KITUI'),
('SOUTH EASTERN KENYA UNIVERSITY DIRECTORATE OF TVET', 'College', 'Public', 'University TVET', 'KITUI'),
('SOUTH EASTERN KENYA UNIVERSITY TVET - MIGWANI', 'College', 'Public', 'University TVET', 'KITUI'),
('SOUTH EASTERN KENYA UNIVERSITY TVET - MTITO ANDEI', 'College', 'Public', 'University TVET', 'MAKUENI'),
('ST JOSEPH''S TECHNICAL INSTITUTE FOR THE DEAF NYANG''OMA', 'College', 'Public', 'Ministry of Education', 'SIAYA'),
('ST PAULS UNIVERSITY', 'University', 'Private', 'Private Institution', 'KIAMBU'),
('ST. AUGUSTINE TEACHERS TRAINING COLLEGE - EREGI', 'College', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('ST. JOHN''S TEACHERS TRAINING COLLEGE - KILIMAMBOGO', 'College', 'Public', 'Ministry of Education', 'KIAMBU'),
('ST. MARKS TEACHERS TRAINING COLLEGE-KIGARI', 'College', 'Public', 'Ministry of Education', 'EMBU'),
('SUBUKIA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAKURU'),
('TAITA TAVETA NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'TAITA TAVETA'),
('TAITA TAVETA UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'TAITA TAVETA'),
('TAITA TAVETA UNIVERSITY INSTITUTE OF TVET', 'College', 'Public', 'University TVET', 'TAITA TAVETA'),
('TAMBACH TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'ELGEYO MARAKWET'),
('TANA RIVER TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TANA RIVER'),
('TANGAZA UNIVERSITY', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('TARBAJ TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'WAJIR'),
('TARBAJ TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'WAJIR'),
('TAVETA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TAITA TAVETA'),
('TECHNICAL UNIVERSITY OF KENYA', 'University', 'Public', 'Ministry of Education', 'NAIROBI'),
('TECHNICAL UNIVERSITY OF MOMBASA', 'University', 'Public', 'Ministry of Education', 'MOMBASA'),
('TECHNICAL UNIVERSITY OF MOMBASA TVET INSTITUTE', 'College', 'Public', 'University TVET', 'MOMBASA'),
('TETU TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYERI'),
('THARAKA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('THARAKA UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'THARAKA NITHI'),
('THARAKA UNIVERSITY TVET INSTITUTE', 'College', 'Public', 'University TVET', 'THARAKA NITHI'),
('THE AFRICAN TALENT UNIVERSITY', 'University', 'Private', 'Private Institution', 'KISUMU'),
('THE BUNGOMA NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'BUNGOMA'),
('THE CO-OPERATIVE UNIVERSITY OF KENYA INSTITUTE OF TVET (CUK - ITVET)', 'College', 'Public', 'University TVET', 'NAIROBI'),
('THE CUK NAIROBI CBD TRAINING INSTITUTE', 'College', 'Public', 'University TVET', 'NAIROBI'),
('THE EAST AFRICAN UNIVERSITY', 'University', 'Private', 'Private Institution', 'KAJIADO'),
('THE NAIROBI NATIONAL POLYTECHNIC', 'College', 'Public', 'Ministry of Education', 'NAIROBI'),
('THE UNIVERSITY OF EMBU TVET INSTITUTE', 'College', 'Public', 'University TVET', 'EMBU'),
('THIKA TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'KIAMBU'),
('THOGOTO TEACHERS TRAINING COLLEGE', 'College', 'Public', 'Ministry of Education', 'KIAMBU'),
('TIGANIA EAST TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MERU'),
('TINDERET INTERGRATED TECHNICAL AND TRAINERS COLLEGE', 'College', 'Public', 'Ministry of Education', 'NANDI'),
('TINDIRET TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NANDI'),
('TOM MBOYA LABOUR COLLEGE', 'College', 'Public', 'NULL', 'KISUMU'),
('TOM MBOYA UNIVERSITY', 'University', 'Public', 'Ministry of Education', 'HOMA BAY'),
('TOTAL TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NAKURU'),
('TSEIKURU TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'KITUI'),
('TUK DIRECTORATE OF TVET COLLEGE', 'College', 'Public', 'University TVET', 'NAIROBI'),
('TURBO TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'UASIN GISHU'),
('TURKANA EAST TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TURKANA'),
('TURKANA NORTH TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TURKANA'),
('TURKANA UNIVERSITY COLLEGE', 'University', 'Public', 'Ministry of Education', 'TURKANA'),
('TURKANA UNIVERSITY TVET INSTITUTE', 'College', 'Public', 'University TVET', 'TURKANA'),
('UGENYA TEACHERS COLLEGE', 'College', 'Public', 'Ministry of Education', 'SIAYA'),
('UGENYA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'SIAYA'),
('UGUNJA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'SIAYA'),
('UNIVERSITY OF EASTERN AFRICA, BARATON', 'University', 'Private', 'Private Institution', 'NANDI'),
('UNIVERSITY OF ELDORET', 'University', 'Public', 'Ministry of Education', 'UASIN GISHU'),
('UNIVERSITY OF EMBU', 'University', 'Public', 'Ministry of Education', 'EMBU'),
('UNIVERSITY OF KABIANGA', 'University', 'Public', 'Ministry of Education', 'KERICHO'),
('UNIVERSITY OF NAIROBI', 'University', 'Public', 'Ministry of Education', 'NAIROBI'),
('URIRI TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MIGORI'),
('UZIMA UNIVERSITY', 'University', 'Private', 'Private Institution', 'KISUMU'),
('WAJIR EAST TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'WAJIR'),
('WAJIR SOUTH TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'WAJIR'),
('WANGA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KAKAMEGA'),
('WATAMU TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KILIFI'),
('WEBUYE WEST TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'BUNGOMA'),
('WERU TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'KILIFI'),
('WEST MUGIRANGO TECHCHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'NYAMIRA'),
('WOTE TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'MAKUENI'),
('WUMINGU TECHNICAL & VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'TAITA TAVETA'),
('YATTA TECHNICAL AND VOCATIONAL COLLEGE', 'College', 'Public', 'Ministry of Education', 'MACHAKOS'),
('ZETECH UNIVERSITY', 'University', 'Private', 'Private Institution', 'NAIROBI'),
('ZIWA TECHNICAL TRAINING INSTITUTE', 'College', 'Public', 'Ministry of Education', 'UASIN GISHU');
